name: Deploy Despacho Backend

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 099875544194.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPOSITORY: innovatech-despacho-backend
  ECS_CLUSTER: innovatech-cluster-1
  ECS_SERVICE: innovatech-despacho-backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4

        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login ECR
        run: aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

      - name: Build y Push imagen a ECR
        run: |
          docker build -t back-despachos Springboot-API-REST-DESPACHO
          docker tag back-despachos:latest ${{ secrets.ECR_REPO_URL_DESPACHOS }}:latest
          docker push ${{ secrets.ECR_REPO_URL_DESPACHOS }}:latest

      - name: Desplegar en EC2 Backend vía SSM
        run: |
          COMMANDS='["set -e","aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}","docker pull ${{ secrets.ECR_REPO_URL_DESPACHOS }}:latest","docker stop back-despachos || true","docker rm back-despachos || true","docker run -d --name back-despachos -p 8081:8081 -e SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }} -e SPRING_DATASOURCE_USERNAME=${{ secrets.MYSQL_USER }} -e SPRING_DATASOURCE_PASSWORD=${{ secrets.MYSQL_PASSWORD }} ${{ secrets.ECR_REPO_URL_DESPACHOS }}:latest"]'
          aws ssm send-command \
            --instance-ids ${{ secrets.EC2_BACKEND_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy back-despachos" \
            --parameters commands="$COMMANDS" \
            --output text

  
      - name: Build imagen
        run: docker build -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest -f ./Dockerfile ./Springboot-API-REST-DESPACHO

      - name: Push a ECR
        run: docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest

      - name: Deploy a ECS
        run: aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_SERVICE }} --force-new-deployment --region ${{ env.AWS_REGION }}

